apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wireguard-ingress
  namespace: glasgow-prod
  labels:
    app: wireguard
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: wireguard.192.168.1.20.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wireguard-service
                port:
                  number: 51821
