apiVersion: v1
kind: Service
metadata:
  name: wireguard-service
  namespace: glasgow-prod
  labels:
    app: wireguard
spec:
  selector:
    app: wireguard
  type: ClusterIP
  ports:
    - name: wireguard-ui
      port: 51821
      targetPort: 51821
      protocol: TCP
