apiVersion: v1
kind: Service
metadata:
  name: wireguard-service
  namespace: glasgow-prod
  labels:
    app: wireguard
spec:
  selector:
    app: wireguard
  type: LoadBalancer
  ports:
    - name: wireguard-udp
      port: 51820
      targetPort: 51820
      protocol: UDP
    - name: wireguard-ui
      port: 51821
      targetPort: 51821
      protocol: TCP
