apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rustfs-console-ingress
  labels:
    app: rustfs
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/backend-protocol: HTTP
    traefik.ingress.kubernetes.io/router.middlewares: glasgow-prod-rustfs-cors@kubernetescrd
spec:
  rules:
  - host: rustfs.192.168.1.20.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rustfs-service
            port:
              number: 9001
