apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-sealed-secret.yaml
- minio-sealed-secret.yaml
- n8n-sealed-secret.yaml
- fastapi-msv2-api-sealed-secret.yaml

namespace: glasgow-prod
