apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-msv2-api-ingress
  namespace: glasgow-prod
  labels:
    app: fastapi-msv2-api
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/passhostheader: "true"
    traefik.ingress.kubernetes.io/frontend-entry-points: web
spec:
  rules:
    - host: msv2-api.192.168.1.20.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi-msv2-api-service
                port:
                  number: 8010