apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-cors-headers
  namespace: glasgow-prod
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      Access-Control-Allow-Origin: "http://msv2-webapp.192.168.1.20.nip.io"
      Access-Control-Allow-Credentials: "true"
      Access-Control-Allow-Methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
      Access-Control-Allow-Headers: "Content-Type, Authorization, Accept, Origin, X-Requested-With"
      Access-Control-Max-Age: "100"