apiVersion: apps/v1
kind: Deployment
metadata:
  name: msv2-webapp
  namespace: glasgow-prod
  labels:
    app: msv2-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msv2-webapp
  template:
    metadata:
      labels:
        app: msv2-webapp
    spec:
      containers:
        - name: msv2-webapp
          image: hatchikin/msv2-webapp:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: msv2-webapp-config
                  key: VITE_API_BASE_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
