apiVersion: v1
kind: Service
metadata:
  name: msv2-webapp-service
  labels:
    app: msv2-webapp
spec:
  selector:
    app: msv2-webapp
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
